VENDEDOR_ID = 0
PRODUCTO_ID = 1
FECHA = 2
CANTIDAD = 3
TOTAL = 4
COLUMNAS= ['ID VENDEDOR', 'PRODUCTO_ID', "FECHA", "CANTIDAD", "TOTAL"]
COLUMNAS1 = ['PRODUCTO_ID', "NOMBRE PRODUCTO", "FECHA", "CANTIDAD", "TOTAL"]